repos:
  - repo: https://github.com/google/pyink
    rev: 24.3.0
    hooks:
      - id: pyink
        # It is recommended to specify the latest version of Python
        # supported by your project here, or alternatively use
        # pre-commit's default_language_version, see
        # https://pre-commit.com/#top_level-default_language_version
        language_version: python3
  - repo: https://github.com/google/pytype
    rev: 2024.10.11
    hooks:
    - id: pytype
      args: ["--config=pytype-conf.cfg"]
