# Copyright 2025 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License

name: Storage Tests

on:
  workflow_call:

permissions:
  contents: read

env:
  CLUSTER_ARGUMENTS: "--network=${{secrets.NETWORK_NAME}} --subnetwork=${{secrets.SUBNETWORK_NAME}}"

jobs:
  create-cluster:
    runs-on: [ubuntu-22.04]
    concurrency: # We support one build or nightly test to run at a time currently.
      group: storage-tests
      cancel-in-progress: true
    steps:
    - uses: actions/download-artifact@v4
      with:
        name: custom-scripts
    - name: Setup environment
      uses: ./.github/actions/setup-test-env
      with:
        credentials_json: "${{ secrets.GCP_SA_KEY }}"
    - name: Check xpk installation
      run: xpk version
    - name: Create cluster
      run: xpk cluster create --cluster xpk-storage-tests --device-type=n2-standard-64-1  --num-slices=1 --zone=us-central2-b --default-pool-cpu-machine-type=n1-standard-16 --default-pool-cpu-num-nodes=2 --on-demand --enable-gcpfilestore-csi-driver --enable-gcsfuse-csi-driver --custom-cluster-arguments="${CLUSTER_ARGUMENTS}"

  delete-cluster:
    runs-on: [ubuntu-22.04]
    needs: [filestore-delete-tests, fuse-detach-tests]
    concurrency: # We support one build or nightly test to run at a time currently.
      group: storage-tests
      cancel-in-progress: true
    if: always()
    steps:
    - uses: actions/download-artifact@v4
      with:
        name: custom-scripts
    - name: Setup environment
      uses: ./.github/actions/setup-test-env
      with:
        credentials_json: "${{ secrets.GCP_SA_KEY }}"
    - name: Check xpk installation
      run: xpk version
    - name: Delete cluster
      if: always()
      run: xpk cluster delete --cluster xpk-storage-tests --zone=us-central2-b --force

  fuse-attach-tests:
    needs: [create-cluster]
    uses: ./.github/workflows/reusable_storage_create.yaml
    concurrency: # We support one build or nightly test to run at a time currently.
      group: fuse-tests
      cancel-in-progress: true
    with:
      cluster-name: xpk-storage-tests
      device-type: n2-standard-64-1
      zone: us-central2-b
      storage-type: 'gcsfuse'
      storage-command: 'attach'
      storage-name: fuse-test
    secrets:
      GCP_SA_KEY: ${{secrets.GCP_SA_KEY}}
      BUCKET_NAME: ${{secrets.BUCKET_NAME}}

  fuse-detach-tests:
    if: always()
    needs: [fuse-attach-tests]
    uses: ./.github/workflows/reusable_storage_delete.yaml
    concurrency: # We support one build or nightly test to run at a time currently.
      group: fuse-tests
    with:
      cluster-name: xpk-storage-tests
      zone: us-central2-b
      storage-type: 'gcsfuse'
      storage-command: 'detach'
      storage-name: fuse-test
    secrets:
      GCP_SA_KEY: ${{secrets.GCP_SA_KEY}}

  filestore-create-tests:
    needs: [fuse-attach-tests]
    uses: ./.github/workflows/reusable_storage_create.yaml
    concurrency: # We support one build or nightly test to run at a time currently.
      group: filestore-tests
      cancel-in-progress: true
    with:
      cluster-name: xpk-storage-tests
      device-type: n2-standard-64-1
      zone: us-central2-b
      storage-type: 'gcpfilestore'
      storage-command: 'create'
      storage-name: gcpfilestore-test
    secrets:
      GCP_SA_KEY: ${{secrets.GCP_SA_KEY}}
      BUCKET_NAME: ${{secrets.BUCKET_NAME}}

  filestore-detach-tests:
    needs: [filestore-create-tests]
    uses: ./.github/workflows/reusable_storage_delete.yaml
    concurrency: # We support one build or nightly test to run at a time currently.
      group: filestore-tests
    with:
      cluster-name: xpk-storage-tests
      zone: us-central2-b
      storage-type: 'gcpfilestore'
      storage-command: 'detach'
      storage-name: gcpfilestore-test
    secrets:
      GCP_SA_KEY: ${{secrets.GCP_SA_KEY}}

  filestore-attach-tests:
    needs: [filestore-detach-tests]
    uses: ./.github/workflows/reusable_storage_create.yaml
    concurrency: # We support one build or nightly test to run at a time currently.
      group: filestore-tests
      cancel-in-progress: true
    with:
      cluster-name: xpk-storage-tests
      device-type: n2-standard-64-1
      zone: us-central2-b
      storage-type: 'gcpfilestore'
      storage-command: 'attach'
      storage-name: gcpfilestore-test
    secrets:
      GCP_SA_KEY: ${{secrets.GCP_SA_KEY}}
      BUCKET_NAME: ${{secrets.BUCKET_NAME}}

  filestore-delete-tests:
    if: always()
    needs: [filestore-create-tests, filestore-attach-tests]
    uses: ./.github/workflows/reusable_storage_delete.yaml
    concurrency: # We support one build or nightly test to run at a time currently.
      group: filestore-tests
    with:
      cluster-name: xpk-storage-tests
      zone: us-central2-b
      storage-type: 'gcpfilestore'
      storage-command: 'delete'
      storage-name: gcpfilestore-test
    secrets:
      GCP_SA_KEY: ${{secrets.GCP_SA_KEY}}

